### ISSUE TITLE
Finishing API endpoints

### ISSUE THREAD

**Issue by fontseca** [fontseca/noda-tasks-management-tool-api#31]
### Authentication

- [x]  **POST**   `/signup`
- [x]  **POST**   `/signin`
- [ ]  **POST**   `/me/logout`
- [ ]  **POST**   `/me/change_password`

### Users

- [x]  **GET**   `/users`
- [x]  **GET**   `/users/search`
- [x]  **GET**   `/users/{user_id}`
- [x] #37
- [x]  **PUT**   `/users/{user_id}/block`
- [x] **DELETE** `/users/{user_id}/block`
- [x]  **GET**   `/users/blocked`
- [x]  **PUT**   `users/{user_id}/make_admin`
- [x] **DELETE** `users/{user_id}/make_admin`
- [x]  **GET**   `/me`
- [x]  **PATCH** `/me`
- [x] **DELETE** `/me`
- [x] #36

### Groups

- [x]   **GET**   `/me/groups`
- [x]  **POST**   `/me/groups`
- [x]   **GET**   `/me/groups/{groups_id}`
- [x]  **PATCH**  `/me/groups/{groups_id}`
- [x] **DELETE**  `/me/groups/{groups_id}`
- [x]   **GET**   `/me/groups/{groups_id}`

### Lists

- [x]   **GET**   `/me/lists`
- [x]  **POST**   `/me/lists`
- [x]   **GET**   `/me/lists/{list_id}`
- [x]  **PATCH**  `/me/lists/{list_id}`
- [x] **DELETE**  `/me/lists/{list_id}`
- [x]   **GET**   `/me/groups/{group_id}/lists`
- [x]  **POST**   `/me/groups/{group_id}/lists`
- [x]   **GET**   `/me/groups/{group_id}/lists/{list_id}`
- [x]  **PATCH**  `/me/groups/{group_id}/lists/{list_id}`
- [x] **DELETE**  `/me/groups/{group_id}/lists/{list_id}`

### Tasks

- [ ]   **GET**   `/me/today`
- [ ]   **GET**   `/me/tomorrow`
- [ ]   **GET**   `/me/tasks`
- [ ]  **POST**   `/me/tasks`
- [ ]   **GET**   `/me/tasks/search`
- [ ]   **GET**   `/me/tasks/completed`
- [ ]   **GET**   `/me/tasks/archived`
- [ ]   **GET**   `/me/tasks/trashed`
- [ ]   **GET**   `/me/tasks/{task_id}`
- [ ]  **PATCH**  `/me/tasks/{task_id}`
- [ ] **DELETE**  `/me/tasks/{task_id}`
- [ ]   **PUT**   `/me/tasks/{task_id}/trash`
- [ ] **DELETE**  `/me/tasks/{task_id}/trash`
- [ ]   **PUT**   `/me/tasks/{task_id}/reorder`
- [ ]   **GET**   `/me/lists/{list_id}/tasks`
- [ ]  **POST**   `/me/lists/{list_id}/tasks`
- [ ]   **GET**   `/me/groups/{group_id}/lists/{list_id}/tasks`
- [ ]  **POST**   `/me/groups/{group_id}/lists/{list_id}/tasks`

### Steps

- [ ]   **GET**   `/me/tasks/{task_id}/steps`
- [ ]  **POST**   `/me/tasks/{task_id}/steps`
- [ ]  **PATCH**  `/me/tasks/{task_id}/steps/{step_id}`
- [ ]   **PUT**   `/me/tasks/{task_id}/steps/{step_id}/accomplish`
- [ ] **DELETE**  `/me/tasks/{task_id}/steps/{step_id}/accomplish`
- [ ] **DELETE**  `/me/tasks/{task_id}/steps/{step_id}`
- [ ]  **POST**   `/me/tasks/{task_id}/steps/{step_id}/reorder`

### Tags

- [ ]   **GET**   `/me/tags`
- [ ]  **POST**   `/me/tags`
- [ ]  **PATCH**  `/me/tags/{tag_id}`
- [ ] **DELETE**  `/me/tags/{tag_id}`

### Attachments

- [ ]   **GET**   `/me/tasks/{task_id}/attachments`
- [ ]   **GET**   `/me/tasks/{task_id}/attachments/{attachment_id}`
- [ ] **DELETE**  `/me/tasks/{task_id}/attachments/{attachment_id}`
